version: "3.8"

services:
  charity:
    build:
      context: ./
      dockerfile: ./charity.Dockerfile
    image: japhethlyh/charity:1.0
    restart: always
    ports: 
     - "5002:5002"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  volunteer:
    build:
      context: ./
      dockerfile: ./volunteer.Dockerfile
    image: japhethlyh/volunteer:1.0
    restart: always
    ports: 
      - "5003:5003"
  
  listing:
    build:
      context: ./
      dockerfile: ./listing.Dockerfile
    image: japhethlyh/listing:1.0
    restart: always
    ports: 
      - "5004:5004"
  
  report:
    build:
      context: ./
      dockerfile: ./report.Dockerfile
    image: japhethlyh/report:1.0
    restart: always
    ports: 
      - "5005:5005"

  users:
    build:
      context: ./
      dockerfile: ./users.Dockerfile
    image: japhethlyh/users:1.0
    restart: always
    ports: 
      - "5006:5006"

  bakery:
    build:
        context: ./
        dockerfile: ./bakery.Dockerfile
    image: japhethlyh/bakery:1.0
    restart: always
    ports: 
      - "5001:5001"
  
  accept_order:
    build:
      context: ./
      dockerfile: ./accept_order.Dockerfile
    image: japhethlyh/accept_order:1.0
    restart: always
    ports: 
      - "5038:5038"
  
  add_listing:
    build:
      context: ./
      dockerfile: ./add_listing.Dockerfile
    image: japhethlyh/add_listing:1.0
    depends_on:
     - listing
    restart: always
    ports: 
      - "5020:5020"

  create_user:
    build:
      context: ./
      dockerfile: ./create_user.Dockerfile
    image: japhethlyh/create_user:1.0
    depends_on:
      - users
    restart: always
    ports: 
      - "5037:5037"

  get_map_info:
    build:
      context: ./
      dockerfile: ./get_map_info.Dockerfile
    image: japhethlyh/get_map_info:1.0
    restart: always
    ports: 
      - "5030:5030"

  release_listing:
    build:
      context: ./
      dockerfile: ./release_listing.Dockerfile
    image: japhethlyh/release_listing:1.0
    restart: always
    depends_on:
     - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    ports: 
      - "5070:5070"

  report_volunteer:
    build:
      context: ./
      dockerfile: ./report_volunteer.Dockerfile
    image: japhethlyh/report_volunteer:1.0
    restart: always
    depends_on:
     - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    ports: 
      - "5069:5069"

  telegram_ms:
    build:
      context: ./
      dockerfile: ./telegram_ms.Dockerfile
    image: japhethlyh/telegram_ms:1.0
    restart: always
    depends_on:
     - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      TELEGRAM_TOKEN: "6160910424:AAFzXahHVctqzM8zD6mLM-Njqe4_f3x4WJ8"
  


  trigger:
    build:
      context: ./
      dockerfile: ./trigger.Dockerfile
    image: japhethlyh/trigger:1.0
    restart: always
  
  update_report:
    build:
      context: ./
      dockerfile: ./update_report.Dockerfile
    image: japhethlyh/update_report:1.0
    restart: always
    ports: 
      - "5041:5041"

volumes:
  rabbitmq_data: